
export const titles: Record<string, string> = {
  "home": "Bienvenido",
  "vendors": "Vendedores",
  "vendors/newVendor": "Creación de nuevo vendedor",
  "vendors/[id]": "Detalles de ${name}",
  "branches/byVendor/[id]": "Tiendas del vendedor ${name}",
  "profile": "Perfil de usuario",
  "users": "Clientes",
  "users/newUser": "Nuevo usuario",
  "branches": "Tiendas",
  "branches/byVendor/[id]/newBranch": "Crear nueva tienda para ${name}",
  "configuration": "Parámetros",
  "disputes": "Disputas",
  "payments": "Pagos",
  "b/home": "Dashboard",
  "b/profile": "Perfil de usuario",
  "branches/[id]": "Detalles de ${name}",
  "products": "Servicios y productos",
  "products/[id]": "Detalles de ${name}",
  "products/byBranch/[id]": "Servicios y productos de la tienda '${name}'",
  "products/byBranch/[id]/newProduct": "Crear un nuevo producto o servicio para la tienda '${name}'",

  "orders" : "Gestión de pedidos",
};
export const subtitles: Record<string, string> = {
  "home": "Resumen general",
  "vendors": "Esta es la pagina de vendedores",
  "vendors/newVendor": "Esta es la pagina de creación de vendedores",
  "vendors/[id]": "Estos son los detalles del veciproveedor",
  "branches/byVendor/[id]": "Listado de tiendas",
  "profile": "Esta es la pagina de perfil de usuario",
  "users": "Esta es la pagina de Clientes",
  "users/newUser": "Esta es la pagina de Nuevo usuario",
  "branches": "Esta es la pagina de tiendas",
  "branches/byVendor/[id]/newBranch": "Esta es la pagina para crear una nueva tienda",
  "configuration": "Esta es la pagina de Parámetros",
  "disputes": "Esta es la pagina de Disputas",
  "payments": "Esta es la pagina de pagos",
  "products": "Esta es la pagina de servicios y productos",
  "products/byBranch/[id]/newProduct": "Esta es la pagina para crear un nuevo producto o servicio",
  "orders": "Administra y monitorea todos los pedidos de tu tienda",
};