
export const titles: Record<string, string> = {
  "/a/home": "Bienvenido",
  "/a/profile": "Perfil de usuario",
  "/a/users": "Clientes",
  "/a/users/newUser": "Nuevo usuario",
  "/a/branches": "Tiendas",
  "/a/branches/newBranch": "Crear nueva tienda para ${name}",
  "/a/vendors": "Vendedores",
  "/a/vendors/newVendor": "Creación de nuevo vendedor",
  "/a/vendors/[id]": "Detalles de ${name}",
  "/a/configuration": "Parámetros",
  "/a/conciliations": "Conciliaciones",
  "/a/payments": "Pagos",
  "/b/home": "Dashboard",
  "/b/profile": "Perfil de usuario",
  "/v/home": "Bienvenido",
  "/v/profile": "Perfil de usuario",
  "/v/branches": "Tiendas",
};
export const subtitles: Record<string, string> = {
  "/a/home": "Resumen general",
  "/a/profile": "Esta es la pagina de perfil de usuario",
  "/a/users": "Esta es la pagina de Clientes",
  "/a/users/newUser": "Esta es la pagina de Nuevo usuario",
  "/a/branches": "Esta es la pagina de tiendas",
  "/a/branches/newBranch": "Esta es la pagina para crear una nueva tienda",
  "/a/vendors": "Esta es la pagina de vendedores",
  "/a/vendors/newVendor": "Esta es la pagina de creación de vendedores",
  "/a/vendors/[id]": "Estos son los detalles del vecirpoveedor",
  "/a/configuration": "Esta es la pagina de Parámetros",
  "/a/conciliations": "Esta es la pagina de conciliaciones",
  "/a/payments": "Esta es la pagina de pagos",
  "/v/home": "Esta es la pagina de Inicio",
  "/v/profile": "Esta es la pagina de perfil de usuario",
  "/v/branches": "Esta es la pagina de tiendas",
};